goal(g).
arc(a,b).
arc(a,c).
arc(a,d).
arc(c,k).
arc(c,f).
arc(d,g).
arc(d,h).
arc(d,i).
arc(f,l).
arc(h,m).
bf([[Start]],Goal,Way).
bf([[Start|Path]|_],Start,[Start|Path]).
bf([[K|Path]|Paths],Start,Solution):-
K\==Start,
bagof([M,K|Path],(way(K,M),\+member(M,[K|Path])),New_Paths),
append(Paths,New_paths,Paths1),
!,
bf(Paths1,Start,Solution);
bf(Paths,Start,Solution).

